# Generated by Django 2.2.24 on 2021-10-25 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_code', models.CharField(max_length=10)),
                ('client_name', models.CharField(max_length=20)),
                ('client_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('office_phone', models.CharField(max_length=15)),
                ('cell_phone', models.CharField(max_length=15)),
                ('prefix', models.CharField(max_length=10)),
                ('is_staff', models.CharField(max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Client')),
            ],
        ),
    ]
