# Generated by Django 2.2.24 on 2021-10-25 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.AutoField(primary_key=True, serialize=False)),
                ('cert_num', models.CharField(max_length=20)),
                ('report_num', models.CharField(max_length=20)),
                ('cert_issue_date', models.DateTimeField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('fax_number', models.CharField(max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('model_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('cell_technology', models.CharField(max_length=20)),
                ('cell_manufacturer', models.CharField(max_length=20)),
                ('num_cells', models.IntegerField()),
                ('num_cells_in_series', models.IntegerField()),
                ('num_series_strings', models.IntegerField()),
                ('num_diodes', models.IntegerField()),
                ('product_length', models.FloatField()),
                ('product_width', models.FloatField()),
                ('product_weight', models.FloatField()),
                ('superstrate_type', models.CharField(max_length=20)),
                ('superstrate_manufacturer', models.CharField(max_length=20)),
                ('substrate_type', models.CharField(max_length=20)),
                ('substrate_manufacturer', models.CharField(max_length=20)),
                ('frame_type', models.CharField(max_length=20)),
                ('frame_adhesive', models.FloatField()),
                ('encapsulant_type', models.CharField(max_length=20)),
                ('encapsulant_manufacturer', models.CharField(max_length=20)),
                ('junction_box_type', models.CharField(max_length=20)),
                ('junction_box_manufacturer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Test_sequence',
            fields=[
                ('sequence_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Test_standard',
            fields=[
                ('standard_id', models.AutoField(primary_key=True, serialize=False)),
                ('standard_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('published_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('is_fi_required', models.CharField(max_length=1)),
                ('fi_frequency', models.FloatField()),
                ('test_standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Test_standard')),
            ],
        ),
        migrations.CreateModel(
            name='Product_factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Performance_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msv', models.FloatField()),
                ('voc', models.FloatField()),
                ('isc', models.FloatField()),
                ('vmp', models.FloatField()),
                ('imp', models.FloatField()),
                ('pmp', models.FloatField()),
                ('ff', models.FloatField()),
                ('model_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Test_sequence')),
            ],
        ),
        migrations.CreateModel(
            name='Factory_inspection',
            fields=[
                ('factory_inspection_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_num', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('inspection_sqeuence', models.CharField(max_length=20)),
                ('finding', models.CharField(max_length=300)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Certificate')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(max_length=20)),
                ('test_standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Test_standard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Location'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='test_standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Test_standard'),
        ),
    ]
